version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=jdbc:postgresql://postgres/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  config-server:
    image: config-server:latest
    container_name: config-server
    build: ./
    ports:
      - 8888:8888
    expose:
      - 8888
    environment:
      - CLOUD=http://config-server:8888
  spring-client:
    container_name: spring-client
    image: spring-client:latest
    depends_on:
      - postgres
      - config-server
    environment:
      CONFIG_SERVER_URI: http://localhost:9001
    ports:
      - 8080:8080
    links:
      - config-server:config-server
    restart: on-failure